### ISSUE TITLE
implement radial layout

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [ConstantinoSchillebeeckx/phylogram_d3#6]
it was originally implemented by @kueda, but since making numerous changes to the original Gist, I've disabled the radial layout for now.

**Comment by kueda** [comment]
You found https://www.jasondavies.com/tree-of-life/ too, right? Probably a better approach than mine.

**Comment by ConstantinoSchillebeeckx** [comment]
I did yes, thanks!

**Comment by ConstantinoSchillebeeckx** [comment]
another great example https://bl.ocks.org/mbostock/c034d66572fd6bd6815a

**Comment by ConstantinoSchillebeeckx** [comment]
Implemented here https://github.com/ConstantinoSchillebeeckx/phylogram_d3/commit/c06f85209437a20aba25fa6898e593eca3efe6c3
